import { jsPDF } from "jspdf";

export const generatePDF = (conversation, title) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  // ==== HEADER BAR ====
  doc.setFillColor(66, 133, 244); // Blue
  doc.rect(0, 0, pageWidth, 25, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(16);
  doc.text("Weather Chat Conversation", 14, 16);

  // ==== META INFO ====
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(12);

  const now = new Date();
  const dateStr = now.toLocaleDateString();
  const timeStr = now.toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" });

  doc.text(`Title: ${title}`, 14, 40);

  const dateTimeStr = `Date: ${dateStr}  |  Time: ${timeStr}`;
  doc.setTextColor(150, 150, 150);
  doc.text(dateTimeStr, pageWidth - 14, 40, { align: "right" });
  doc.setTextColor(0, 0, 0);

  doc.setDrawColor(50, 50, 50);
  doc.setLineWidth(0.5);
  doc.line(14, 45, pageWidth - 14, 45);

  // ==== MESSAGES ====
  let y = 55;
  let lastRole = null;

  conversation.messages.forEach((msg, index) => {
    const sender = msg.role === "user" ? "You" : "Weather Agent";
    const timestamp = msg.timestamp.toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" });

    // Role-based style for sender info
    if (msg.role === "user") {
      doc.setTextColor(33, 150, 243);
      doc.setFont("helvetica", "bold");
    } else {
      doc.setTextColor(85, 85, 85);
      doc.setFont("helvetica", "normal");
    }
    
    // --- MODIFIED LAYOUT LOGIC ---
    const headerX = 14;
    const contentX = 80;
    const contentWidth = pageWidth - contentX - 14; 

    doc.setFontSize(11);
    const header = `${index + 1}. ${sender} (${timestamp}) -`;
    doc.text(header, headerX, y);

    doc.setFontSize(11);
    doc.setTextColor(0, 0, 0); 
    const splitText = doc.splitTextToSize(msg.content, contentWidth);
    doc.text(splitText, contentX, y);
 
    y += splitText.length * 6 + 8; 
 
    if (msg.role === "agent" && lastRole === "user") {
      doc.setDrawColor(200, 200, 200);
      doc.setLineWidth(0.2);
      doc.line(14, y - 4, pageWidth - 14, y - 4); 
      y += 5;
    }

    lastRole = msg.role;

    // Page break if needed
    if (y > 270) {
      doc.addPage();
      y = 20;
    }
  });

  // ==== FOOTER ====
  doc.setFontSize(10);
  doc.setTextColor(150, 150, 150);
  doc.text("Generated by Weather Chat Assistant", 14, 285);

  // Save PDF
  doc.save(
    `weather-chat-${title.replace(/[^a-z0-9]/gi, "_").toLowerCase()}.pdf`
  );
};